# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'JLGlobalAdBanner' do
pod 'Google-Mobile-Ads-SDK'
pod 'JLThemeHelper', '~> 2.1'
#pod 'Cent'
end

target 'JLGlobalAdBannerTests' do

end

